configfile: "consistent_config.json"
REC = config.get("REC")
SIMTYPE = config.get("SIMTYPE")
RES = config.get("RES")
STRICT = config.get("STRICT")
ROUNDS = config.get("ROUNDS")
CONSISTENT = config.get("CONSISTENT")
FINAL_NO_RESOLVE = config.get("FINAL_NO_RESOLVE")
PRE_RESOLVE = config.get("PRE_RESOLVE")
METRIC = config.get("METRIC")

rule all:
    input:
        "results.zip"

rule precompile_script:
    message:
        "precompile julia script"
    output:
        "mcc_accuracy_simulations.so",
    shell:
        """
        julia --project=../../. build_sys_image.jl
        rm -r results
        """

rule run_simulations:
    message:
        "start simulations in julia"
    input:
        "mcc_accuracy_simulations.so"
    output:
        "results/results_{simtype}_{res}_{strict}_{rounds}_{pre_resolve}_{consistent}_{final_no_resolve}/results_{metric}_{rec}.txt"
    params: 
        n_leaves = config.get("n"),
        rounds  = config.get("sim"),
    wildcard_constraints:
        rec = "(-4.0|-3.75|-3.5|-3.25|-3.0|-2.75|-2.5|-2.25|-2.0|-1.75|-1.5|-1.25|-1.0|-0.75|-0.5|-0.25|0.0)",
        strict = "(true|false)", 
        simtype = "(flu|kingman)",
        res = "(0.1|0.2|0.25|0.3|0.35|0.4)",
        rounds = "(1|2|3)",
        consistent = "(true|false)",
        final_no_resolve = "(true|false)",
        pre_resolve = "(true|false)",
        metric = "(VI|rand|v-measure-complete|v-measure-homogenity)",
    shell:
     """
        julia -J mcc_accuracy_simulations.so --project=../../.  ../MCC_accuracy_simulations.jl --o "results/results_{wildcards.simtype}_{wildcards.res}_{wildcards.strict}_{wildcards.rounds}_{wildcards.pre_resolve}_{wildcards.consistent}_{wildcards.final_no_resolve}/" --metric {wildcards.metric} --rec {wildcards.rec} --n {params.n_leaves} --sim {params.rounds} --strict {wildcards.strict} --simtype {wildcards.simtype} --res {wildcards.res} --rounds {wildcards.rounds} --krange false --consistent {wildcards.consistent} --final-no-resolve {wildcards.final_no_resolve} --pre-resolve {wildcards.pre_resolve} 
     """

rule plot_graphs:
    input:
        expand(["results/results_{simtype}_{res}_{strict}_{rounds}_{pre_resolve}_{consistent}_{final_no_resolve}/results_{metric}_{rec}.txt"], rec=REC, metric=METRIC, strict=STRICT, simtype=SIMTYPE, res=RES, rounds=ROUNDS, consistent=CONSISTENT, final_no_resolve=FINAL_NO_RESOLVE, pre_resolve=PRE_RESOLVE)
    output:
        "Plots.zip"
    shell:
        """
        mkdir Plots
        julia --project=../../. Plots.jl
        zip -rm Plots.zip Plots
        """

rule zip:
    input:
        expand(["results/results_{simtype}_{res}_{strict}_{rounds}_{pre_resolve}_{consistent}_{final_no_resolve}/results_{metric}_{rec}.txt"], rec=REC, metric=METRIC, strict=STRICT, simtype=SIMTYPE, res=RES, rounds=ROUNDS, consistent=CONSISTENT, final_no_resolve=FINAL_NO_RESOLVE, pre_resolve=PRE_RESOLVE),
        "Plots.zip"
    output:
        "results.zip"
    shell:
        """
        zip -rm results.zip results
        """