configfile: "mcc_config.json"
REC = config.get("REC")
SIMTYPE = config.get("SIMTYPE")
RES = config.get("RES")
STRICT = config.get("STRICT")

METRIC =["v-measure-complete", "v-measure-homogenity"]

rule all:
    input:
        "results.zip"

rule precompile_script:
    message:
        "precompile julia script"
    output:
        "mcc_accuracy_simulations.so",
    shell:
        """
        julia --project=../. build_sys_image.jl
        rm -r results
        """

rule run_simulations:
    message:
        "start simulations in julia"
    input:
        "mcc_accuracy_simulations.so"
    output:
        "results/results_{simtype}_{res}_{strict}/results_{m}_{rec}.txt",
    params: 
        n_leaves = config.get("n"),
        rounds  = config.get("sim"),
    wildcard_constraints:
        rec = "(-4.0|-3.75|-3.5|-3.25|-3.0|-2.75|-2.5|-2.25|-2.0|-1.75|-1.5|-1.25|-1.0|-0.75|-0.5|-0.25|0.0)",
        m = "(rand|VI|v-measure-complete|v-measure-homogenity)",
        strict = "(true|false)", 
        simtype = "(flu|kingman)",
        res = "(0.1|0.2|0.25|0.3|0.35|0.4)",
    shell:
     """
        julia -J mcc_accuracy_simulations.so --project=../.  MCC_accuracy_simulations.jl --o "results/results_{wildcards.simtype}_{wildcards.res}_{wildcards.strict}/" --rec {wildcards.rec} --n {params.n_leaves} --sim {params.rounds} --metric {wildcards.m} --strict {wildcards.strict} --simtype {wildcards.simtype} --res {wildcards.res}
     """

rule plot_graphs:
    input:
        expand(["results/results_{simtype}_{res}_{strict}/results_{m}_{rec}.txt"], rec=REC, m=METRIC, strict=STRICT, simtype=SIMTYPE, res=RES)
    output:
        "Plots.zip"
    shell:
        """
        mkdir Plots
        julia --project=../. PlotGraphs.jl
        zip -rm Plots.zip Plots
        """

rule zip:
    input:
        expand(["results/results_{simtype}_{res}_{strict}/results_{m}_{rec}.txt"], rec=REC, m=METRIC, strict=STRICT, simtype=SIMTYPE, res=RES),
        "Plots.zip"
    output:
        "results.zip"
    shell:
        """
        zip -rm results.zip results
        """